/**
 * Copyright (c) 2024, DEPHAN LLC, Anton Ledrov
 * All rights reserved.
 */

/**
 * @file ros_driver.hpp
 * @brief ROS driver for DEPHAN LLC LiDars
 */

#ifndef DRIVER_HPP
#define DRIVER_HPP

#include <ros/ros.h>
#include <atomic>
#include <memory>
#include <string>
#include <sensor_msgs/LaserScan.h>
#include <sensor_msgs/PointCloud2.h>
#include <std_msgs/String.h>
#include <std_msgs/UInt8MultiArray.h>
#include <visualization_msgs/MarkerArray.h>
#include <pcl_ros/point_cloud.h>
#include <tins/tins.h>
#include <thread>
#include <chrono>

#include "packet_raw.hpp"
#include "reciever_socket.hpp"
#include "packet_handler_mech.hpp"

namespace dephan_ros {
/**
 * Runtime ROS publication and debug options.
 */
struct DriverRuntimeOptions {
    /**
     * Topic for PointCloud2 data derived from LaserScan ranges.
     */
    std::string pointcloud_topic;

    /**
     * Frame id written to LaserScan, PointCloud2 and safety debug messages.
     */
    std::string frame_id = "base_link";

    /**
     * Angle offset in radians applied to scan angles and zone visualization.
     */
    double angle_offset_rad = 1.5707963267948966;

    /**
     * Enables optional safety zone marker and status topic publication.
     */
    bool safety_debug = false;

    /**
     * HTTP endpoint used by safety debug polling.
     */
    std::string http_host = "192.168.0.120";
    int http_port         = 80;
    int http_timeout_ms   = 3000;

    /**
     * Safety debug topic names and polling period.
     */
    std::string safety_zones_topic  = "safety_zones_markers";
    std::string safety_status_topic = "safety_zones_status";
    double safety_debug_period_s    = 1.0;
};

/**
 * Base class for driver.
 */
class Driver {
private:
    /**
     * IP address of the LiDar device.
     */
    std::string ip_addr;

    /**
     * Port of the LiDar device.
     */
    unsigned port;

    /**
     * Socket pointer for recieving data.
     */
    std::unique_ptr<receiver_socket> socket;

    /**
     * Path to pcap file that will be readed by driver.
     */
    std::string pcap_path;

    /**
     * Pointer in libtins' shiffer
     */
    std::unique_ptr<Tins::FileSniffer> pcap_sniffer;

    /**
     * Stored packet's timestamp for time correct reading from the pcap file.
     */
    long long _prev_pkt_tmstmp;

    /**
     * Ros topic publisher for the ros laserscan data.
     */
    ros::Publisher laserscan_publisher;

    /**
     * Ros topic publisher for point cloud data derived from LaserScan points.
     */
    ros::Publisher pointcloud_publisher;

    /**
     * MarkerArray publisher for optional RViz safety zone visualization.
     */
    ros::Publisher safety_zones_publisher;

    /**
     * String publisher with raw /zones/status.json data.
     */
    ros::Publisher safety_status_publisher;

    /**
     * Runtime ROS and optional debug settings.
     */
    DriverRuntimeOptions runtime_options;

    /**
     * Last wall-clock time when safety debug data was polled over HTTP.
     */
    std::chrono::steady_clock::time_point last_safety_debug_publish;

    /**
     * Background worker for safety debug polling.
     */
    std::atomic_bool safety_debug_running{false};
    std::thread safety_debug_thread;

    /**
     * Publish safety zone markers and status JSON when debug mode is enabled.
     */
    void publish_safety_debug();

    /**
     * Poll one packet (2 pi / 18 rad segment per packet) in UDP mode.
     */
    void _poll_udp();

    /**
     * Poll one packet (2 pi / 18 rad segment per packet) in PCAP mode.
     */
    void _poll_pcap();

    /**
     * Poll 18 packets (2 pi rad segment per packet) in UPD mode.
     */
    void _poll_full_udp();

    /**
     * Pill 18 packets (2 pi rad segment per packet) in PCAP mode.
     */
    void _poll_full_pcap();

public:
    /**
     * Stops optional background safety debug polling.
     */
    ~Driver();

    /**
     * Driver UDP mode constructor.
     *
     * @param[in] nh Ros handle node.
     * @param[in] ip_addr Ip address of the LiDar device.
     * @param[in] port Network port of the LiDar device.
     * @param[in] topic_name Name of the LaserScan topic generated by the Driver.
     * @param[in] runtime_options ROS publication and optional debug settings.
     */
    Driver(
        ros::NodeHandle nh, std::string ip_addr, unsigned port,
        std::string topic_name,
        DriverRuntimeOptions runtime_options = DriverRuntimeOptions()
    );

    /**
     * Driver PCAP mode construcror.
     *
     * @param[in] nh Ros handle node.
     * @param[in] pcap_path Path to the target PCAP file.
     * @param[in] topic_name Name of the LaserScan topic generated by the Driver.
     * @param[in] runtime_options ROS publication and optional debug settings.
     */
    Driver(
        ros::NodeHandle nh, std::string pcap_path, std::string topic_name,
        DriverRuntimeOptions runtime_options = DriverRuntimeOptions()
    );

    /**
     * Polling function for the one packet from the LiDar.
     */
    void poll();

    /**
     * Polling function for the full revolution from the LiDar.
     */
    void poll_full();

    /**
     * Getter for the network parameters of the LiDar device.
     */
    std::pair<std::string, unsigned> get_network_params();
};
} // namespace dephan_ros

#endif
