services:
  ros1-noetic:
    build:
      context: .
      dockerfile: ros1-noetic.Dockerfile
    image: dephan-ros-driver:ros1-noetic
    stdin_open: true
    tty: true
    ports:
      - "50007:50007/udp"
    volumes:
      - ${DRIVER_WORKSPACE:-..}:/workspace
