services:
  ros2-jazzy:
    build:
      context: .
      dockerfile: ros2-jazzy.Dockerfile
    image: dephan-ros-driver:ros2-jazzy
    stdin_open: true
    tty: true
    ports:
      - "50007:50007/udp"
    volumes:
      - ${DRIVER_WORKSPACE:-..}:/workspace
