name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs: 
  docs:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip3 install sphinx sphinx_copybutton sphinx_tabs sphinx_rtd_theme sphinx_favicon
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_9_1/doxygen-1.9.1.linux.bin.tar.gz
          tar xzvf doxygen-1.9.1.linux.bin.tar.gz
          cd doxygen-1.9.1
          sudo make install
          cd ..
          rm -rf doxygen-1.9.1* 
      - name: Documentation build
        run: |
          make html 
      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
