name: documentation

on: [push, pull_request, workflow_dispatch]
    
permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx breathe sphinx_copybutton sphinx_tabs sphinx_rtd_theme sphinx_favicon
          sudo apt install doxygen

      - name: Build main
        working-directory: ./src/docs
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          export CURRENT_VERSION=docs
          make html 

      - name: Build ros1
        working-directory: ./src/docs
        if: ${{ github.ref == 'refs/heads/ros1' }}
        run: |
          export CURRENT_VERSION=ROS:noetic
          git fetch origin main:main
          git checkout main -- source/conf.py
          make html 

      - name: Build ros2
        working-directory: ./src/docs
        if: ${{ github.ref == 'refs/heads/ros2' }}
        run: |
          export CURRENT_VERSION=ROS:iron
          git fetch origin main:main
          git checkout main -- source/conf.py
          make html 

      - name: Deploy Greetings to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/docs/build/html
          destination_dir: docs
          enable_jekyll: false

      - name: Deploy ROS:noetic version to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/ros1'}}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/docs/build/html
          destination_dir: noetic
          enable_jekyll: false

      - name: Deploy ROS:iron version to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/ros2'}}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/docs/build/html
          destination_dir: iron
          enable_jekyll: false

